import React, { useCallback, useEffect, useState } from "react";
import { ExternalLink, RefreshCw, Newspaper } from "lucide-react";
const DEFAULT_NEWS_URL="https://min-api.cryptocompare.com/data/v2/news/?lang=EN&sortOrder=latest";
function timeAgo(value){const ts=Number(value)*1000;if(!Number.isFinite(ts))return "";const diff=Math.max(0,Date.now()-ts),m=Math.floor(diff/60000);if(m<1)return "just now";if(m<60)return `${m}m ago`;const h=Math.floor(m/60);if(h<24)return `${h}h ago`;return `${Math.floor(h/24)}d ago`;}
function normalise(items){return(Array.isArray(items)?items:[]).filter(i=>i?.title).slice(0,8).map(i=>({id:i.id||i.url||i.title,title:i.title,description:i.body||i.description||"",image:i.imageurl||"",publishedAt:i.published_on,url:i.url||"#",source:i.source_info?.name||i.source||"Crypto News"}));}
export default function SpaceNewsSection(){
 const[items,setItems]=useState([]),[status,setStatus]=useState("loading");
 const load=useCallback(async()=>{setStatus(items.length?"refreshing":"loading");try{const endpoint=import.meta.env.VITE_SPACE_NEWS_URL||DEFAULT_NEWS_URL;const response=await fetch(endpoint,{headers:{Accept:"application/json"}});if(!response.ok)throw new Error("News request failed");const payload=await response.json();const next=normalise(payload?.Data||payload?.data||payload?.articles);if(!next.length)throw new Error("No news returned");setItems(next);setStatus("ready");}catch{setStatus(items.length?"ready":"error");}},[items.length]);
 useEffect(()=>{load();const id=window.setInterval(load,300000);return()=>window.clearInterval(id);},[load]);
 return <section style={{margin:"18px 14px 26px"}}>
  <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:12}}><div><div style={{fontFamily:"Montserrat,sans-serif",fontWeight:800,fontSize:22,color:"#0F0E0B",letterSpacing:-.4}}>Space News</div><div style={{marginTop:2,fontFamily:"Montserrat,sans-serif",fontSize:11,color:"#8B8476",fontWeight:600}}>Market moves, crypto &amp; macro headlines</div></div><button onClick={load} aria-label="Refresh news" style={{width:36,height:36,borderRadius:12,border:"1px solid #E9E4D8",background:"#fff",color:"#8B8476",display:"grid",placeItems:"center",cursor:"pointer"}}><RefreshCw size={15} style={{animation:status==="refreshing"?"rx-news-spin .9s linear infinite":"none"}}/></button></div>
  {status==="loading"&&<div style={{display:"grid",gap:10}}>{[0,1,2].map(i=><div key={i} style={{height:96,borderRadius:18,background:"linear-gradient(90deg,#fff,#f4f1e8,#fff)",border:"1px solid #EEE9DD"}}/>)}</div>}
  {status==="error"&&<div style={{background:"#fff",border:"1px solid #E9E4D8",borderRadius:18,padding:"20px 16px",textAlign:"center"}}><Newspaper size={22} color="#B9AD93"/><div style={{fontFamily:"Montserrat,sans-serif",fontWeight:700,fontSize:13,color:"#0F0E0B",marginTop:7}}>News is taking a quick breather.</div><div style={{fontFamily:"Montserrat,sans-serif",fontSize:11,color:"#8B8476",margin:"5px 0 12px"}}>Pull to refresh or try again in a moment.</div><button onClick={load} style={{border:"none",background:"#F4D35E",color:"#0F0E0B",borderRadius:10,padding:"9px 14px",fontWeight:800,cursor:"pointer"}}>Try again</button></div>}
  {status!=="loading"&&items.length>0&&<div style={{display:"grid",gap:10}}>{items.slice(0,5).map(item=><a key={item.id} href={item.url} target="_blank" rel="noreferrer" style={{display:"flex",gap:12,alignItems:"center",textDecoration:"none",background:"#fff",border:"1px solid #EEE9DD",borderRadius:18,padding:10,boxShadow:"0 4px 18px rgba(15,14,11,.05)"}}><div style={{width:82,height:76,flexShrink:0,borderRadius:14,overflow:"hidden",background:"linear-gradient(135deg,#F4D35E,#F5F0E4)",display:"grid",placeItems:"center"}}>{item.image?<img src={item.image} alt="" loading="lazy" style={{width:"100%",height:"100%",objectFit:"cover"}}/>:<Newspaper size={24} color="#8B6F22"/>}</div><div style={{minWidth:0,flex:1}}><div style={{display:"flex",justifyContent:"space-between",gap:8,marginBottom:4}}><span style={{fontFamily:"Montserrat,sans-serif",fontSize:9.5,fontWeight:800,color:"#B08A18",textTransform:"uppercase",letterSpacing:.5}}>{item.source}</span><span style={{fontFamily:"Montserrat,sans-serif",fontSize:9.5,color:"#A29A8A",whiteSpace:"nowrap"}}>{timeAgo(item.publishedAt)}</span></div><div style={{fontFamily:"Montserrat,sans-serif",fontSize:13,lineHeight:1.28,fontWeight:800,color:"#0F0E0B",display:"-webkit-box",WebkitLineClamp:2,WebkitBoxOrient:"vertical",overflow:"hidden"}}>{item.title}</div><div style={{fontFamily:"Montserrat,sans-serif",fontSize:10.5,lineHeight:1.35,color:"#777061",marginTop:4,display:"-webkit-box",WebkitLineClamp:2,WebkitBoxOrient:"vertical",overflow:"hidden"}}>{item.description}</div></div><ExternalLink size={14} color="#B9AD93" style={{flexShrink:0}}/></a>)}</div>}
  <style>{`@keyframes rx-news-spin{from{transform:rotate(0deg)}to{transform:rotate(360deg)}}`}</style>
 </section>;
}
