kind = "web"
previewPath = "/"
title = "RainX"
version = "1.0.0"
id = "artifacts/rainx"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18895

[services.development]
run = "pnpm --filter @workspace/rainx run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/rainx", "run", "build" ]
serve = "static"
publicDir = "artifacts/rainx/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18895"
BASE_PATH = "/"
